# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\"*\n\nConnection\x12\x0e\n\x06\x63onnip\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\tServerAck\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\"J\n\x06\x41\x63tion\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x10\n\x08targetid\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0e\n\x06params\x18\x04 \x01(\t\".\n\x06Lookup\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x14\n\x0clast_message\x18\x02 \x01(\x05\"f\n\x06Update\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x11\n\tplayerids\x18\x02 \x03(\x05\x12\x13\n\x0bplayernames\x18\x03 \x03(\t\x12\x12\n\nplayerstat\x18\x04 \x03(\x05\x12\x10\n\x08messages\x18\x05 \x03(\t26\n\x11\x43onnectionService\x12!\n\x06\x61\x63\x63\x65pt\x12\x0b.Connection\x1a\n.ServerAck2,\n\rUpdateService\x12\x1b\n\x07process\x12\x07.Lookup\x1a\x07.Update2.\n\rActionService\x12\x1d\n\x06\x63ommit\x12\x07.Action\x1a\n.ServerAckb\x06proto3')



_CONNECTION = DESCRIPTOR.message_types_by_name['Connection']
_SERVERACK = DESCRIPTOR.message_types_by_name['ServerAck']
_ACTION = DESCRIPTOR.message_types_by_name['Action']
_LOOKUP = DESCRIPTOR.message_types_by_name['Lookup']
_UPDATE = DESCRIPTOR.message_types_by_name['Update']
Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'transport_pb2'
  # @@protoc_insertion_point(class_scope:Connection)
  })
_sym_db.RegisterMessage(Connection)

ServerAck = _reflection.GeneratedProtocolMessageType('ServerAck', (_message.Message,), {
  'DESCRIPTOR' : _SERVERACK,
  '__module__' : 'transport_pb2'
  # @@protoc_insertion_point(class_scope:ServerAck)
  })
_sym_db.RegisterMessage(ServerAck)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'transport_pb2'
  # @@protoc_insertion_point(class_scope:Action)
  })
_sym_db.RegisterMessage(Action)

Lookup = _reflection.GeneratedProtocolMessageType('Lookup', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUP,
  '__module__' : 'transport_pb2'
  # @@protoc_insertion_point(class_scope:Lookup)
  })
_sym_db.RegisterMessage(Lookup)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'transport_pb2'
  # @@protoc_insertion_point(class_scope:Update)
  })
_sym_db.RegisterMessage(Update)

_CONNECTIONSERVICE = DESCRIPTOR.services_by_name['ConnectionService']
_UPDATESERVICE = DESCRIPTOR.services_by_name['UpdateService']
_ACTIONSERVICE = DESCRIPTOR.services_by_name['ActionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTION._serialized_start=19
  _CONNECTION._serialized_end=61
  _SERVERACK._serialized_start=63
  _SERVERACK._serialized_end=103
  _ACTION._serialized_start=105
  _ACTION._serialized_end=179
  _LOOKUP._serialized_start=181
  _LOOKUP._serialized_end=227
  _UPDATE._serialized_start=229
  _UPDATE._serialized_end=331
  _CONNECTIONSERVICE._serialized_start=333
  _CONNECTIONSERVICE._serialized_end=387
  _UPDATESERVICE._serialized_start=389
  _UPDATESERVICE._serialized_end=433
  _ACTIONSERVICE._serialized_start=435
  _ACTIONSERVICE._serialized_end=481
# @@protoc_insertion_point(module_scope)
